print("Aniket said ,  \npython is Awesome!")

print("Let's learn \nPython programming \ntogether.")   
print("This is line one.\nThis is line two.\n\tThis line is indented.")
print("C:\\Users\\Aniket\\Documents\\Python")
print("She said, \"Python is fun!\"")
print('It\'s a beautiful day to learn Python!')
print("Path to the folder: C:\\new_folder\\python_files")
print("First Line\nSecond Line\n\tIndented Line\nThird Line")
print("He exclaimed, \"Learning Python is exciting!\"")
print('It\'s important to practice coding every day!')
print("To use a backslash, type \\\\ in your string.")
print("This is the first line.\nThis is the second line with a tab:\n\t- Item 1\n\t- Item 2")
print("She said, \"It's a wonderful day to code!\"")
print('It\'s a great day to learn Python programming!')