print("Hello!wrold ") 
print("how are you?") 
print("I am fine, thank you!")
print("What about you?")    
print("I am doing well too!")
print("That's great to hear!")
print("Yes, indeed!")
print("What are your plans for today?")
print("I plan to go for a walk.")
print("Sounds like a good idea!")
